# Use the Bun official image to avoid installing it manually
FROM oven/bun:latest

# Actualiza el sistema e instala OpenSSL
RUN apt-get update -y \
    && apt-get install -y openssl

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and bun.lockb to install dependencies
COPY package.json bun.lockb .env ./startup.sh ./

# Da permisos al script
RUN chmod +x ./startup.sh

# Install project dependencies using Bun
RUN bun install

# Copy the rest of the source code
COPY . .

# Expose the port where the application runs (adjust if needed)
EXPOSE 3000

# Command to start the application
CMD ["./startup.sh"]
